name: CI Pipeline  
on: [push]  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - name: Build  
        run: make
      - uses: actions/upload-artifact@v4  
        with:  
          name: build-artifact  
          path: hello